#!/usr/bin/env php
<?php

class Main {
	public function run() {
		if ($this->hasUnsavedChanges()) {
			$this->commitChanges();
			$this->pushChanges();
		}
	}

	public function hasUnsavedChanges() {
		exec('git status', $output, $status);
		return $output[1] !== 'nothing to commit (working directory clean)';
	}

	public function commitChanges() {
		$message = "Backup commit on: " . date('H:i:s d.m.Y');
		exec('git add . && git status', $output, $status);
		$message .= chr(10) . implode(chr(10), $output);
		$message = str_replace('"', '\'', $message);
		exec('git commit -a -m "' . $message . '"', $output, $status);
	}

	public function pushChanges() {
		exec('git push origin master', $output, $status);
	}
}

$app = new Main();
$app->run();

?>
